import { readFileSync, writeFileSync } from "node:fs"
import grouping from "./grouping.js"
import questionnaire from "./questionnaire.js"
import type { Answer } from "./type.js"

const SCORES: { value: string; display: Answer["answer"] }[] = [
  { value: "3", display: "+3" },
  { value: "2", display: "+2" },
  { value: "1", display: "+1" },
  { value: "0", display: "0" },
  { value: "9", display: "-1" },
  { value: "8", display: "-2" },
  { value: "7", display: "-3" },
]

const HTML_ESCAPES: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;",
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => HTML_ESCAPES[c] ?? c)
}

function renderForm(): string {
  const entries = Object.entries(questionnaire)
  const parts: string[] = []
  for (const [majorKey, major] of Object.entries(grouping)) {
    parts.push(`<section>`)
    parts.push(`<h2>${escapeHtml(major.label)}</h2>`)
    for (const [minorKey, minor] of Object.entries(major.minor)) {
      parts.push(`<h3>--- ${escapeHtml(minor.label)} ---</h3>`)
      for (const [key, q] of entries) {
        if (q.majorGroup !== majorKey || q.minorGroup !== minorKey) {
          continue
        }
        parts.push(`<fieldset>`)
        parts.push(`<legend>&gt; ${escapeHtml(q.question)}</legend>`)
        parts.push(`<span class="score-end score-agree">同意</span>`)
        for (const { value, display } of SCORES) {
          const id = `${key}__${value}`
          const checked = value === "0" ? " checked" : ""
          parts.push(
            `<label class="score-option" for="${id}">` +
              `<input id="${id}" type="radio" name="${key}" ` +
              `value="${value}" required${checked}>` +
              `${display}` +
              `</label>`,
          )
        }
        parts.push(`<span class="score-end score-disagree">不同意</span>`)
        parts.push(`</fieldset>`)
      }
    }
    parts.push(`</section>`)
  }
  return parts.join("\n")
}

const questionnaireUrl = new URL("./questionnaire.js", import.meta.url)
const questionnaireSrc = readFileSync(questionnaireUrl, "utf8").replace(
  /^export default /m,
  "const questionnaire = ",
)
const scriptUrl = new URL("./index.js", import.meta.url)
const scriptSrc = readFileSync(scriptUrl, "utf8").replace(
  /^import questionnaire from "\.\/questionnaire\.js";?\n?/m,
  "",
)
const script = `${questionnaireSrc}\n${scriptSrc}`
const formHtml = renderForm()

function renderPromptQuestionnaire(): string {
  const parts: string[] = []
  for (const [key, q] of Object.entries(questionnaire)) {
    parts.push(`- ${key}: ${q.question}`)
  }
  return parts.join("\n")
}

const onlineUrl = new URL("https://abti.mptree.com/")
const formattedQuestionnaire = renderPromptQuestionnaire()
const prompt = `
你正在做 ABTI（Agent Bias Type Indicator）测试——一个为程序员设计的 MBTI
风格性格测试。对于下面的每条陈述，请选择最符合你日常实际工作方式的答案，
而不是你期望的方式。请诚实作答——否则结果没有参考价值。

你的立场选项：
  - 非常同意（strong agree）
  - 同意（agree）
  - 略微同意（weak agree）
  - 略微不同意（weak disagree）
  - 不同意（disagree）
  - 非常不同意（strong disagree）

题目（key: 陈述）：
${formattedQuestionnaire}


回答完所有题目后，请按以下格式构建结果 URL：
${onlineUrl}?name=name&question1_key=standing&question2_key=standing&...
name 是你的显示名称。
每个 key 来自上面的题目列表，每个 standing 是一位数字：
3 代表非常同意，2 代表同意，1 代表略微同意，9 代表略微不同意，8 代表不同意，7 代表非常不同意。
然后告诉我打开结果 URL 查看结果。
`

const html = `<!doctype html>
<!-- This file is generated by build.ts. Do not edit. -->
<html lang="zh-Hans">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ABTI - 智能体偏好类型指标</title>
    <meta name="description" content="ABTI 是一款专为程序员设计的 MBTI 风格性格测试。基于日常真实工作决策，发现你的编码人格，而非生活方式偏好。">
    <meta name="keywords" content="ABTI, MBTI, 性格测试, 程序员, 开发者, 编码人格, 智能体偏好类型指标">
    <meta property="og:title" content="ABTI - 智能体偏好类型指标">
    <meta property="og:description" content="专为程序员设计的 MBTI 风格性格测试。基于你的真实工作方式，发现你的编码人格。">
    <meta property="og:type" content="website">
    <meta property="og:url" content="${onlineUrl}">
    <style>
      * { margin: 0; padding: 0; }
      html { background: #380c2a; }
      body {
        margin: 0;
        color: #eeeeee;
        font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace;
      }
      p, fieldset, pre {
        max-width: 1024px;
        margin-left: auto;
        margin-right: auto;
        margin-top: 1rem;
        margin-bottom: 1rem;
      }
      h1 {
        text-align: center;
        padding-top: 2rem;
        padding-bottom: 0.5rem;
      }
      #github {
        text-align: center;
      }
      #subtitle {
        display: flex;
        align-items: center;
        justify-content: center;
        color: #888888;
        text-align: center;
        font-size: 1.25rem;
        margin-top: 0.5rem;
        margin-bottom: 0.5rem;
      }
      h2 {
        color: black;
        background-color: #a2734c;
        text-align: center;
        margin-top: 2rem;
        margin-bottom: 2rem;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
      }
      h3 {
        color: #888888;
        text-align: center;
        margin-top: 2rem;
        margin-bottom: 2rem;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
      }
      fieldset {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-wrap: wrap;
        margin-bottom: 2rem;
        border: none;
        padding: 0;
      }
      fieldset legend { flex-basis: 100%; margin-bottom: 1rem; }
      .score-option {
        --c: #888888;
        position: relative;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 2.5rem;
        height: 2.5rem;
        padding: 0;
        margin-left: 0.5rem;
        margin-right: 0.5rem;
        border: 2px solid;
        border-color: var(--c);
        border-radius: 30%;
        color: var(--c);
        line-height: 1;
        cursor: pointer;
        user-select: none;
      }
      .score-option input {
        position: absolute;
        opacity: 0;
        width: 0;
        height: 0;
      }
      .score-option:has(input[value="7"]) { --c: #ee0000ff; }
      .score-option:has(input[value="8"]) { --c: #ee0000bb; }
      .score-option:has(input[value="9"]) { --c: #ee000088; }
      .score-option:has(input[value="0"])  { --c: #888888; }
      .score-option:has(input[value="1"]) { --c: #00770088; }
      .score-option:has(input[value="2"]) { --c: #007700bb; }
      .score-option:has(input[value="3"]) { --c: #007700ff; }
      .score-option:has(input:checked) {
        background-color: var(--c);
        color: #380c2a;
      }
      .score-option:has(input:focus-visible) {
        outline: 2px solid white;
        outline-offset: 2px;
      }
      .score-end {
        min-width: 3rem;
        margin-left: 0.5rem;
        margin-right: 0.5rem;
        text-align: center;
      }
      .score-disagree { color: #ff0000; }
      .score-agree { color: #00aa00; }
      .submit {
        display: block;
        margin: 2rem auto;
        padding: 0.75rem 2rem;
        font-size: 1.25rem;
      }
      #abti-result {
        max-width: 1024px;
        margin-left: auto;
        margin-right: auto;
        background: #12488b;
        color: #eeeeee;
        padding-top: 2rem;
        padding-bottom: 2rem;
      }
      #abti-code-label {
        text-align: center;
      }
      #abti-code {
        text-align: center;
        font-size: 4rem;
        margin-bottom: 1rem;
      }
      #mbti-link, #abti-link {
        display: block;
        text-align: center;
        color: #e2732d;
        text-decoration: none;
        margin-top: 1rem;
        margin-bottom: 1rem;
      }
      .abti-dimension {
        display: flex;
        align-items: center;
        margin-top: 1rem;
        margin-bottom: 1rem;
      }
      .abti-half {
        flex: 1 1 0;
        min-width: 0;
        display: flex;
        align-items: center;
      }
      .abti-half-neg {
        justify-content: flex-end;
      }
      .abti-half-pos {
        justify-content: flex-start;
      }
      .abti-neg {
        text-align: right;
        margin-right: 1rem;
      }
      .abti-pos {
        text-align: left;
        margin-left: 1rem;
      }
      .abti-dimension-label {
        text-align: center;
        color: #888888;
      }
      .abti-fence {
        margin-left: 0.5rem;
        margin-right: 0.5rem;
      }
      #prompt-label {
        color: #e2732d;
      }
      #prompt-container {
        max-width: 1024px;
        margin-left: auto;
        margin-right: auto;
      }
      #prompt-show, #prompt-hide, #prompt-copy {
        display: inline-block;
        margin: 0.5rem auto;
      }
      #prompt-buttons {
        text-align: center;
      }
      #name-container {
        text-align: center;
        margin: 2rem auto;
        max-width: 1024px;
      }
      #name-input {
        padding: 0.5rem 1rem;
        min-width: 240px;
      }
      @media (max-width: 600px) {
        .abti-bar { display: none; }
        .score-end { display: none; }
        .score-option {
          margin-left: 0.25rem;
          margin-right: 0.25rem;
        }
      }
      #abti-result { display: none; }
      #abti-result.visible { display: block; }
      #prompt-show { display: none; }
      #prompt-show.visible { display: inline-block; }
      #prompt-hide { display: none; }
      #prompt-hide.visible { display: inline-block; }
      #prompt { display: none; }
      #prompt.visible { display: block; }
      .beian {
        display: block;
        text-align: center;
        color: #e9ad0c;
        text-decoration: none;
        margin-top: 1rem;
        margin-bottom: 1rem;
      }
    </style>
  </head>
  <body>
    <h1>ABTI - Agent Bias Type Indicator</h1>
    <div id="github">
      <a class="github-button" href="https://github.com/bigmapletree/abti" data-color-scheme="no-preference: light; light: light; dark: dark;" data-size="large" data-show-count="true" aria-label="Star bigmapletree/abti on GitHub">Star</a>
    </div>
    <p id="subtitle">
      为硅基马农设计的人格测试<br/>
      (碳基马农也能测)
    </p>
    <div id="abti-result">
      <p id="abti-code-label"><span id="abti-user-name"></span> ABTI 硅基马农人格为</p>
      <div id="abti-code"></div>
      <a id="mbti-link" href="#" target="_blank"></a>
      <p class="abti-dimension-label">--- 与他人互动时 ---</p>
      <div class="abti-dimension">
        <div class="abti-half abti-half-neg">
          <div id="abti-extraverted" class="abti-neg"></div>
          <div id="abti-extraverted-bar" class="abti-bar"></div>
        </div>
        <div class="abti-fence">|</div>
        <div class="abti-half abti-half-pos">
          <div id="abti-introverted-bar" class="abti-bar"></div>
          <div id="abti-introverted" class="abti-pos"></div>
        </div>
      </div>
      <p class="abti-dimension-label">--- 决定行动时 ---</p>
      <div class="abti-dimension">
        <div class="abti-half abti-half-neg">
          <div id="abti-intuitive" class="abti-neg"></div>
          <div id="abti-intuitive-bar" class="abti-bar"></div>
        </div>
        <div class="abti-fence">|</div>
        <div class="abti-half abti-half-pos">
          <div id="abti-observant-bar" class="abti-bar"></div>
          <div id="abti-observant" class="abti-pos"></div>
        </div>
      </div>
      <p class="abti-dimension-label">--- 行动过程中最重视 ---</p>
      <div class="abti-dimension">
        <div class="abti-half abti-half-neg">
          <div id="abti-thinking" class="abti-neg"></div>
          <div id="abti-thinking-bar" class="abti-bar"></div>
        </div>
        <div class="abti-fence">|</div>
        <div class="abti-half abti-half-pos">
          <div id="abti-feeling-bar" class="abti-bar"></div>
          <div id="abti-feeling" class="abti-pos"></div>
        </div>
      </div>
      <p class="abti-dimension-label">--- 行动风格是 ---</p>
      <div class="abti-dimension">
        <div class="abti-half abti-half-neg">
          <div id="abti-judging" class="abti-neg"></div>
          <div id="abti-judging-bar" class="abti-bar"></div>
        </div>
        <div class="abti-fence">|</div>
        <div class="abti-half abti-half-pos">
          <div id="abti-prospecting-bar" class="abti-bar"></div>
          <div id="abti-prospecting" class="abti-pos"></div>
        </div>
      </div>
      <a id="abti-link" href="${onlineUrl}" target="_blank">
        获取测试提示词： ${onlineUrl} 
      </a>
    </div>
    <p id="initiative">
      马农在生活中和工作中的表现往往有所不同，而标准 MBTI 捕捉了更多生活层面的特征。
      ABTI 舍弃了生活方向的题目，专注于每天实际写代码场景中的具体选择，
      从而确保测试结果更加忠实反映测试者在大型软件项目中的真实行为，帮助马农更好地评估与同事的合作方式。
    </p>
    <p id="introduction">
      阅读每条陈述，根据你实际的工作方式（而非期望的方式）选择你的立场。
      选项为：非常同意（+3）、同意（+2）、略微同意（+1）、略微不同意（-1）、不同意（-2）、非常不同意（-3）。
      请回答每一道题，只有诚实作答，结果才有参考价值。
    </p>
    <p id="usage">
      本测试被设计用于调教编程智能体的行为模式。
      在智能体的 MEMORY.md 里写入你想要的人格，让他重新测试，直到智能体满足你的期待为止。
      相信我，你需要一个P人设计功能，和一个J人将功能落地。
    </p>
    <p id="prompt-label">
      如需让你的智能体测试，请将提示词复制粘贴给他：
      <button id="prompt-show" class="visible" type="button">展开提示词</button>
      <button id="prompt-hide" type="button">隐藏提示词</button>
      <button id="prompt-copy" type="button">一键复制提示词</button>
    </p>
    <pre id="prompt">${escapeHtml(prompt)}</pre>
    <form id="abti-form" method="get">
${formHtml}
      <div id="name-container">
        <label for="name-input">你的名字</label>
        <input id="name-input" name="name" type="text" placeholder="（可选，仅用于展示）">
      </div>
      <button class="submit" type="submit">提交</button>
    </form>
    <script type="module">
${script}
    </script>
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <p class="beian">© 2026 Mapletree LLC 大枫树科技 版权所有</p>
    <a class="beian" href="https://beian.miit.gov.cn/">京ICP备2024094947号</a>
  </body>
</html>
`

const outUrl = new URL("./index.html", import.meta.url)
writeFileSync(outUrl, html)
console.log(`wrote ${outUrl.pathname}`)

const promptUrl = new URL("./prompt.txt", import.meta.url)
writeFileSync(promptUrl, prompt)
console.log(`wrote ${promptUrl.pathname}`)
