import { readFileSync, writeFileSync } from "node:fs"
import grouping from "./grouping.js"
import questionnaire from "./questionnaire.js"
import type { Answer } from "./type.js"

const SCORES: { value: string; display: Answer["answer"] }[] = [
  { value: "3", display: "+3" },
  { value: "2", display: "+2" },
  { value: "1", display: "+1" },
  { value: "0", display: "0" },
  { value: "9", display: "-1" },
  { value: "8", display: "-2" },
  { value: "7", display: "-3" },
]

const HTML_ESCAPES: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;",
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => HTML_ESCAPES[c] ?? c)
}

function renderForm(): string {
  const entries = Object.entries(questionnaire)
  const parts: string[] = []
  for (const [majorKey, major] of Object.entries(grouping)) {
    parts.push(`<section>`)
    parts.push(`<h2>${escapeHtml(major.label)}</h2>`)
    for (const [minorKey, minor] of Object.entries(major.minor)) {
      parts.push(`<h3>--- ${escapeHtml(minor.label)} ---</h3>`)
      for (const [key, q] of entries) {
        if (q.majorGroup !== majorKey || q.minorGroup !== minorKey) {
          continue
        }
        parts.push(`<fieldset>`)
        parts.push(`<legend>&gt; ${escapeHtml(q.question)}</legend>`)
        parts.push(`<span class="score-end score-agree">Agree</span>`)
        for (const { value, display } of SCORES) {
          const id = `${key}__${value}`
          const checked = value === "0" ? " checked" : ""
          parts.push(
            `<label class="score-option" for="${id}">` +
              `<input id="${id}" type="radio" name="${key}" ` +
              `value="${value}" required${checked}>` +
              `${display}` +
              `</label>`,
          )
        }
        parts.push(`<span class="score-end score-disagree">Disagree</span>`)
        parts.push(`</fieldset>`)
      }
    }
    parts.push(`</section>`)
  }
  return parts.join("\n")
}

const questionnaireUrl = new URL("./questionnaire.js", import.meta.url)
const questionnaireSrc = readFileSync(questionnaireUrl, "utf8").replace(
  /^export default /m,
  "const questionnaire = ",
)
const scriptUrl = new URL("./index.js", import.meta.url)
const scriptSrc = readFileSync(scriptUrl, "utf8").replace(
  /^import questionnaire from "\.\/questionnaire\.js";?\n?/m,
  "",
)
const script = `${questionnaireSrc}\n${scriptSrc}`
const formHtml = renderForm()

function renderPromptQuestionnaire(): string {
  const parts: string[] = []
  for (const [key, q] of Object.entries(questionnaire)) {
    parts.push(`- ${key}: ${q.question}`)
  }
  return parts.join("\n")
}

const onlineUrl = new URL("https://bigmapletree.github.io/abti/")
const formattedQuestionnaire = renderPromptQuestionnaire()
const prompt = `
You're taking the ABTI (Agent Bias Type Indicator) test — an MBTI-style
personality test for coders. For each statement below, pick the answer
that matches how you actually work day-to-day, not how you wish you
worked. Be honest — otherwise the result won't tell you anything useful.

Your standings are:
  - strong agree
  - agree
  - weak agree
  - weak disagree
  - disagree
  - strong disagree

Questions (key: statement):
${formattedQuestionnaire}


Once you've answered them all, build a result URL in this format:
${onlineUrl}?name=name&question1_key=standing&question2_key=standing&...
Name is your display name.
Each key comes from the list above, and each standing is a single digit:
3 for strong agree, 2 for agree, 1 for weak agree, 9 for weak disagree, 8 for disagree, 7 for strong disagree.
Then tell me to go to the result URL for the results.
`

const html = `<!doctype html>
<!-- This file is generated by build.ts. Do not edit. -->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ABTI - Agent Bias Type Indicator</title>
    <meta name="description" content="ABTI is an MBTI-style personality test designed for coders. Discover your coding personality based on real day-to-day work decisions, not lifestyle preferences.">
    <meta name="keywords" content="ABTI, MBTI, personality test, coder, developer, coding personality, agent bias type indicator">
    <meta property="og:title" content="ABTI - Agent Bias Type Indicator">
    <meta property="og:description" content="An MBTI-style personality test for coders. Find out your coding personality based on how you actually work.">
    <meta property="og:type" content="website">
    <meta property="og:url" content="${onlineUrl}">
    <style>
      * { margin: 0; padding: 0; }
      html { background: #380c2a; }
      body {
        margin: 0;
        color: #eeeeee;
        font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace;
      }
      p, fieldset, pre {
        max-width: 1024px;
        margin-left: auto;
        margin-right: auto;
        margin-top: 1rem;
        margin-bottom: 1rem;
      }
      h1 {
        text-align: center;
        padding-top: 2rem;
        padding-bottom: 0.5rem;
      }
      #github {
        text-align: center;
      }
      #subtitle {
        display: flex;
        align-items: center;
        justify-content: center;
        color: #888888;
        text-align: center;
        font-size: 1.25rem;
        margin-top: 0.5rem;
        margin-bottom: 0.5rem;
      }
      h2 {
        color: black;
        background-color: #a2734c;
        text-align: center;
        margin-top: 2rem;
        margin-bottom: 2rem;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
      }
      h3 {
        color: #888888;
        text-align: center;
        margin-top: 2rem;
        margin-bottom: 2rem;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
      }
      fieldset {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-wrap: wrap;
        margin-bottom: 2rem;
        border: none;
        padding: 0;
      }
      fieldset legend { flex-basis: 100%; margin-bottom: 1rem; }
      .score-option {
        --c: #888888;
        position: relative;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 2.5rem;
        height: 2.5rem;
        padding: 0;
        margin-left: 0.5rem;
        margin-right: 0.5rem;
        border: 2px solid;
        border-color: var(--c);
        border-radius: 30%;
        color: var(--c);
        line-height: 1;
        cursor: pointer;
        user-select: none;
      }
      .score-option input {
        position: absolute;
        opacity: 0;
        width: 0;
        height: 0;
      }
      .score-option:has(input[value="7"]) { --c: #ee0000ff; }
      .score-option:has(input[value="8"]) { --c: #ee0000bb; }
      .score-option:has(input[value="9"]) { --c: #ee000088; }
      .score-option:has(input[value="0"])  { --c: #888888; }
      .score-option:has(input[value="1"]) { --c: #00770088; }
      .score-option:has(input[value="2"]) { --c: #007700bb; }
      .score-option:has(input[value="3"]) { --c: #007700ff; }
      .score-option:has(input:checked) {
        background-color: var(--c);
        color: #380c2a;
      }
      .score-option:has(input:focus-visible) {
        outline: 2px solid white;
        outline-offset: 2px;
      }
      .score-end {
        min-width: 3rem;
        margin-left: 0.5rem;
        margin-right: 0.5rem;
        text-align: center;
      }
      .score-disagree { color: #ff0000; }
      .score-agree { color: #00aa00; }
      .submit {
        display: block;
        margin: 2rem auto;
        padding: 0.75rem 2rem;
        font-size: 1.25rem;
      }
      #abti-result {
        max-width: 1024px;
        margin-left: auto;
        margin-right: auto;
        background: #12488b;
        color: #eeeeee;
        padding-top: 2rem;
        padding-bottom: 2rem;
      }
      #abti-code-label {
        text-align: center;
      }
      #abti-code {
        text-align: center;
        font-size: 4rem;
        margin-bottom: 1rem;
      }
      #mbti-link, #abti-link {
        display: block;
        text-align: center;
        color: #e2732d;
        text-decoration: none;
        margin-top: 1rem;
        margin-bottom: 1rem;
      }
      .abti-dimension {
        display: flex;
        align-items: center;
        margin-top: 1rem;
        margin-bottom: 1rem;
      }
      .abti-half {
        flex: 1 1 0;
        min-width: 0;
        display: flex;
        align-items: center;
      }
      .abti-half-neg {
        justify-content: flex-end;
      }
      .abti-half-pos {
        justify-content: flex-start;
      }
      .abti-neg {
        text-align: right;
        margin-right: 1rem;
      }
      .abti-pos {
        text-align: left;
        margin-left: 1rem;
      }
      .abti-dimension-label {
        text-align: center;
        color: #888888;
      }
      .abti-fence {
        margin-left: 0.5rem;
        margin-right: 0.5rem;
      }
      #prompt-label {
        color: #e2732d;
      }
      #prompt-container {
        max-width: 1024px;
        margin-left: auto;
        margin-right: auto;
      }
      #prompt-show, #prompt-hide, #prompt-copy {
        display: inline-block;
        margin: 0.5rem auto;
      }
      #prompt-buttons {
        text-align: center;
      }
      #name-container {
        text-align: center;
        margin: 2rem auto;
        max-width: 1024px;
      }
      #name-input {
        padding: 0.5rem 1rem;
        min-width: 240px;
      }
      @media (max-width: 600px) {
        .abti-bar { display: none; }
        .score-end { display: none; }
        .score-option {
          margin-left: 0.25rem;
          margin-right: 0.25rem;
        }
      }
      #abti-result { display: none; }
      #abti-result.visible { display: block; }
      #prompt-show { display: none; }
      #prompt-show.visible { display: inline-block; }
      #prompt-hide { display: none; }
      #prompt-hide.visible { display: inline-block; }
      #prompt { display: none; }
      #prompt.visible { display: block; }
    </style>
  </head>
  <body>
    <h1>ABTI - Agent Bias Type Indicator</h1>
    <div id="github">
      <a class="github-button" href="https://github.com/bigmapletree/abti" data-color-scheme="no-preference: light; light: light; dark: dark;" data-size="large" data-show-count="true" aria-label="Star bigmapletree/abti on GitHub">Star</a>
    </div>
    <p id="subtitle">
      The MBTI personality test for (agent) coders.
    </p>
    <div id="abti-result">
      <p id="abti-code-label"><span id="abti-user-name"></span> ABTI coding personality is</p>
      <div id="abti-code"></div>
      <a id="mbti-link" href="#" target="_blank"></a>
      <p class="abti-dimension-label">--- How you interact with others ---</p>
      <div class="abti-dimension">
        <div class="abti-half abti-half-neg">
          <div id="abti-extraverted" class="abti-neg"></div>
          <div id="abti-extraverted-bar" class="abti-bar"></div>
        </div>
        <div class="abti-fence">|</div>
        <div class="abti-half abti-half-pos">
          <div id="abti-introverted-bar" class="abti-bar"></div>
          <div id="abti-introverted" class="abti-pos"></div>
        </div>
      </div>
      <p class="abti-dimension-label">--- How you pick what to do next ---</p>
      <div class="abti-dimension">
        <div class="abti-half abti-half-neg">
          <div id="abti-intuitive" class="abti-neg"></div>
          <div id="abti-intuitive-bar" class="abti-bar"></div>
        </div>
        <div class="abti-fence">|</div>
        <div class="abti-half abti-half-pos">
          <div id="abti-observant-bar" class="abti-bar"></div>
          <div id="abti-observant" class="abti-pos"></div>
        </div>
      </div>
      <p class="abti-dimension-label">--- What matters most when you decide ---</p>
      <div class="abti-dimension">
        <div class="abti-half abti-half-neg">
          <div id="abti-thinking" class="abti-neg"></div>
          <div id="abti-thinking-bar" class="abti-bar"></div>
        </div>
        <div class="abti-fence">|</div>
        <div class="abti-half abti-half-pos">
          <div id="abti-feeling-bar" class="abti-bar"></div>
          <div id="abti-feeling" class="abti-pos"></div>
        </div>
      </div>
      <p class="abti-dimension-label">--- What drives your work ---</p>
      <div class="abti-dimension">
        <div class="abti-half abti-half-neg">
          <div id="abti-judging" class="abti-neg"></div>
          <div id="abti-judging-bar" class="abti-bar"></div>
        </div>
        <div class="abti-fence">|</div>
        <div class="abti-half abti-half-pos">
          <div id="abti-prospecting-bar" class="abti-bar"></div>
          <div id="abti-prospecting" class="abti-pos"></div>
        </div>
      </div>
      <a id="abti-link" href="${onlineUrl}" target="_blank">
        Please visit ${onlineUrl} to take the test.
      </a>
    </div>
    <p id="initiative">
      People act differently in life and at work, and MBTI mostly picks up the lifestyle side. 
      ABTI drops the lifestyle questions and sticks to concrete day-to-day coding choices,
      which keeps the profile honest about real behavior on a coding project and
      makes it easier to figure out how to collaborate with your coworkers better.
    </p>
    <p id="introduction">
      Read each statement and choose your standing based on how you actually work, not how you wish you worked. 
      The standings are strong agree (+3), agree (+2), weak agree (+1), weak disagree (-1), disagree (-2), and strong disagree (-3). 
      Answer every question — the result is only useful if your answers are honest.
    </p>
    <p id="usage">
      This test was built to help you tune your coding agent's behavior. 
      Tweak your agent's MEMORY.md with the personality you want, 
      rerun the test to check how its bias shifts, 
      and dial it in until the agent works the way you like.
      Trust me, you need a P agent to design your features, and a J agent to execute them.
    </p>
    <p id="prompt-label">
      For your coding agent to test, please copy paste the following prompt 
      to your agent: 
      <button id="prompt-show" class="visible" type="button">show prompt</button>
      <button id="prompt-hide" type="button">hide prompt</button>
      <button id="prompt-copy" type="button">copy prompt</button>
    </p>
    <pre id="prompt">${escapeHtml(prompt)}</pre>
    <form id="abti-form" method="get">
${formHtml}
      <div id="name-container">
        <label for="name-input">Name</label>
        <input id="name-input" name="name" type="text" placeholder="(optional, only used for display)">
      </div>
      <button class="submit" type="submit">Submit</button>
    </form>
    <script type="module">
${script}
    </script>
    <script async defer src="https://buttons.github.io/buttons.js"></script>
  </body>
</html>
`

const outUrl = new URL("./index.html", import.meta.url)
writeFileSync(outUrl, html)
console.log(`wrote ${outUrl.pathname}`)

const promptUrl = new URL("./prompt.txt", import.meta.url)
writeFileSync(promptUrl, prompt)
console.log(`wrote ${promptUrl.pathname}`)
