import type { Question } from "./type.js"

export default {
  A1: {
    key: "A1",
    majorGroup: "team-planning",
    minorGroup: "talk-peer",
    question:
      "与同事一起规划时，轮到我发言时我更愿意用一句话概括，而不是一次性列出所有细节。",
    weight: { introverted: 1, observant: -2, feeling: 0, prospecting: 1 },
  },
  A2: {
    key: "A2",
    majorGroup: "team-planning",
    minorGroup: "talk-owner",
    question:
      "与负责人一起规划时，轮到我发言时我更愿意用一句话概括，而不是一次性列出所有细节。",
    weight: { introverted: 1, observant: -2, feeling: -1, prospecting: 1 },
  },
  A3: {
    key: "A3",
    majorGroup: "team-planning",
    minorGroup: "talk-report",
    question:
      "与下属一起规划时，轮到我发言时我更愿意用一句话概括，而不是一次性列出所有细节。",
    weight: { introverted: 1, observant: -2, feeling: -1, prospecting: 1 },
  },
  A4: {
    key: "A4",
    majorGroup: "team-planning",
    minorGroup: "talk-pm",
    question:
      "与项目经理一起规划时，轮到我发言时我更愿意用一句话概括，而不是一次性列出所有细节。",
    weight: { introverted: 1, observant: -2, feeling: 0, prospecting: 1 },
  },
  A5: {
    key: "A5",
    majorGroup: "team-code-review",
    minorGroup: "review-peer",
    question: "审查同事代码时，我更愿意留一句话总结，而不是逐一过每个细节。",
    weight: { introverted: 1, observant: -2, feeling: 0, prospecting: 1 },
  },
  A6: {
    key: "A6",
    majorGroup: "team-code-review",
    minorGroup: "review-owner",
    question: "审查负责人代码时，我更愿意留一句话总结，而不是逐一过每个细节。",
    weight: { introverted: 1, observant: -2, feeling: -1, prospecting: 1 },
  },
  A7: {
    key: "A7",
    majorGroup: "team-code-review",
    minorGroup: "review-report",
    question: "审查下属代码时，我更愿意留一句话总结，而不是逐一过每个细节。",
    weight: { introverted: 1, observant: -2, feeling: -1, prospecting: 1 },
  },
  B: {
    key: "B",
    majorGroup: "team-code-review",
    minorGroup: "review-report",
    question:
      "在下属的代码审查中给予表扬比在同事的审查中更重要——这能校准他们对「好」的标准。",
    weight: { introverted: -1, observant: -1, feeling: 2, prospecting: -1 },
  },
  BP: {
    key: "BP",
    majorGroup: "personal-firming-up",
    minorGroup: "think-security",
    question: "比起因为理论风险而搁置，我更愿意先发布功能，之后再修补漏洞。",
    weight: { introverted: 0, observant: -2, feeling: -2, prospecting: 2 },
  },
  C: {
    key: "C",
    majorGroup: "team-planning",
    minorGroup: "talk-peer",
    question: "我先想好方案再分享——过早讨论浪费大家的时间。",
    weight: { introverted: 2, observant: -1, feeling: -2, prospecting: -1 },
  },
  C2: {
    key: "C2",
    majorGroup: "personal-planning",
    minorGroup: "break-project",
    question:
      "开始前把任务分解成小块，对我接手的大多数工作来说感觉像过度规划。",
    weight: { introverted: -1, observant: -1, feeling: 0, prospecting: 2 },
  },
  C4: {
    key: "C4",
    majorGroup: "personal-writing-code",
    minorGroup: "structure-code",
    question: "比起还没见到真实代码就设计抽象，我更愿意重构一个能跑的原型。",
    weight: { introverted: 0, observant: -1, feeling: 0, prospecting: 3 },
  },
  CF: {
    key: "CF",
    majorGroup: "personal-firming-up",
    minorGroup: "think-security",
    question:
      "安全检查有实际成本，所以我只在风险真实存在的地方做——而不是到处都做。",
    weight: { introverted: 0, observant: 1, feeling: -1, prospecting: 1 },
  },
  Cd: {
    key: "Cd",
    majorGroup: "team-planning",
    minorGroup: "talk-pm",
    question:
      "项目经理要权衡许多我看不到的人和优先级——比起质疑，我更信任他们的排序。",
    weight: { introverted: 0, observant: 1, feeling: 0, prospecting: 0 },
  },
  Ce: {
    key: "Ce",
    majorGroup: "team-code-review",
    minorGroup: "review-report",
    question: "我用和自己相同的标准要求下属的代码——甚至更高，为了他们好。",
    weight: { introverted: -1, observant: 1, feeling: -1, prospecting: -1 },
  },
  D: {
    key: "D",
    majorGroup: "team-code-review",
    minorGroup: "review-owner",
    question: "当我认为代码负责人有误时，我会像对同事一样坚定地反驳。",
    weight: { introverted: -2, observant: -1, feeling: -2, prospecting: 0 },
  },
  Dc: {
    key: "Dc",
    majorGroup: "team-emotional",
    minorGroup: "sit-owner",
    question: "一次激烈交锋后，我会暂时避开代码负责人，让事情冷却一下。",
    weight: { introverted: 3, observant: -1, feeling: 2, prospecting: 0 },
  },
  Dq: {
    key: "Dq",
    majorGroup: "team-emotional",
    minorGroup: "sit-owner",
    question:
      "我会在一对一沟通中处理代码负责人的尖锐评论，而不是在原来的讨论帖里。",
    weight: { introverted: 1, observant: 1, feeling: 2, prospecting: 0 },
  },
  E: {
    key: "E",
    majorGroup: "personal-writing-code",
    minorGroup: "polish-code",
    question:
      "写干净的代码某种程度上是一种尊重——对下一个读者，也对六个月后的自己。",
    weight: { introverted: 0, observant: -1, feeling: 1, prospecting: 0 },
  },
  E8: {
    key: "E8",
    majorGroup: "personal-firming-up",
    minorGroup: "think-security",
    question: "对新设计做威胁建模这件事，我大概比团队其他人更享受。",
    weight: { introverted: 2, observant: 0, feeling: -1, prospecting: -1 },
  },
  EI: {
    key: "EI",
    majorGroup: "team-planning",
    minorGroup: "talk-pm",
    question:
      "好的项目经理带给我的是问题而非解决方案——如果需求文档读起来像设计文档，我会质疑。",
    weight: { introverted: -2, observant: -2, feeling: -2, prospecting: 1 },
  },
  EO: {
    key: "EO",
    majorGroup: "team-code-review",
    minorGroup: "take-owner",
    question: "通过代码负责人的审查而没有太多评论，感觉像一次个人胜利。",
    weight: { introverted: 1, observant: 1, feeling: 2, prospecting: -1 },
  },
  F: {
    key: "F",
    majorGroup: "personal-writing-code",
    minorGroup: "shape-commits",
    question:
      "我写提交信息时会考虑审查者（或未来的自己），而不仅仅是自动化工具。",
    weight: { introverted: 0, observant: 0, feeling: 1, prospecting: -1 },
  },
  F0: {
    key: "F0",
    majorGroup: "team-code-review",
    minorGroup: "take-owner",
    question:
      "我对待代码负责人的审查评论和其他人的一样——我采纳站得住脚的那些。",
    weight: { introverted: -1, observant: 1, feeling: -2, prospecting: 0 },
  },
  FG: {
    key: "FG",
    majorGroup: "team-planning",
    minorGroup: "talk-owner",
    question:
      "如果我对方案有信心，我会先写好 PR，让代码负责人对实际代码做出反应。",
    weight: { introverted: 1, observant: -2, feeling: -2, prospecting: 2 },
  },
  Fd: {
    key: "Fd",
    majorGroup: "team-emotional",
    minorGroup: "sit-owner",
    question: "代码负责人的尖锐言辞只是信号——我不会往人身攻击上想。",
    weight: { introverted: -2, observant: 1, feeling: -2, prospecting: 1 },
  },
  Fr: {
    key: "Fr",
    majorGroup: "team-code-review",
    minorGroup: "review-owner",
    question: "审查代码负责人的代码时，我会比审查同事的更注意措辞。",
    weight: { introverted: -1, observant: 1, feeling: 1, prospecting: -1 },
  },
  H: {
    key: "H",
    majorGroup: "personal-firming-up",
    minorGroup: "explore-code",
    question: "改动重要代码行之前，我会查看 git blame——上下文就在历史记录里。",
    weight: { introverted: 1, observant: 0, feeling: 0, prospecting: -1 },
  },
  H0: {
    key: "H0",
    majorGroup: "personal-writing-code",
    minorGroup: "shape-commits",
    question: "提交就是存档点——我不在意它之后看起来什么样。",
    weight: { introverted: -1, observant: -1, feeling: -1, prospecting: 2 },
  },
  HU: {
    key: "HU",
    majorGroup: "team-planning",
    minorGroup: "talk-report",
    question: "交接任务时，我会列出我自己希望别人给我的那些具体约束条件。",
    weight: { introverted: 2, observant: 2, feeling: 1, prospecting: -2 },
  },
  HX: {
    key: "HX",
    majorGroup: "personal-writing-code",
    minorGroup: "scope-task",
    question: "每当我碰一个文件时，我都会有想重写周围代码的冲动。",
    weight: { introverted: 0, observant: -1, feeling: 1, prospecting: 2 },
  },
  Hz: {
    key: "Hz",
    majorGroup: "team-emotional",
    minorGroup: "sit-owner",
    question: "代码负责人的一句重话能打乱我一整周的节奏。",
    weight: { introverted: 3, observant: -1, feeling: 3, prospecting: 0 },
  },
  I: {
    key: "I",
    majorGroup: "personal-writing-code",
    minorGroup: "shape-commits",
    question:
      "理想情况下，每个提交应该只做一件事，即使这意味着要拆分一个完整的改动。",
    weight: { introverted: 0, observant: 0, feeling: 0, prospecting: -1 },
  },
  I1: {
    key: "I1",
    majorGroup: "personal-firming-up",
    minorGroup: "handle-debt",
    question: "我会持续记录我注意到的技术债，以便日后提议一次集中清理。",
    weight: { introverted: 1, observant: 1, feeling: 1, prospecting: -3 },
  },
  K: {
    key: "K",
    majorGroup: "team-planning",
    minorGroup: "talk-report",
    question: "我会让下属在问题上先摸索一阵再介入——这样他们学到的更多。",
    weight: { introverted: 1, observant: -1, feeling: 1, prospecting: 2 },
  },
  KA: {
    key: "KA",
    majorGroup: "personal-writing-code",
    minorGroup: "structure-code",
    question: "我自顶向下构建——先勾勒控制流，再填充细节。",
    weight: { introverted: 0, observant: -2, feeling: 0, prospecting: -1 },
  },
  KT: {
    key: "KT",
    majorGroup: "personal-writing-code",
    minorGroup: "write-todos",
    question: "留 TODO 时，我会标注负责人和原因，方便以后接手。",
    weight: { introverted: -1, observant: 2, feeling: 0, prospecting: -1 },
  },
  KTf: {
    key: "KTf",
    majorGroup: "team-code-review",
    minorGroup: "review-peer",
    question: "如果我会用不同的方式解决，我会在审查中说出来——同事可以反驳。",
    weight: { introverted: -2, observant: -2, feeling: -2, prospecting: 0 },
  },
  Kj: {
    key: "Kj",
    majorGroup: "personal-planning",
    minorGroup: "pick-dependency",
    question: "每个新依赖都是长期负担，所以我倾向于自己写最少必要的代码。",
    weight: { introverted: 2, observant: -2, feeling: -2, prospecting: -1 },
  },
  L: {
    key: "L",
    majorGroup: "team-code-review",
    minorGroup: "take-report",
    question: "忽略下属明显离谱的审查评论没什么问题——我没必要回应每一条。",
    weight: { introverted: -1, observant: -1, feeling: -3, prospecting: 1 },
  },
  Li: {
    key: "Li",
    majorGroup: "personal-planning",
    minorGroup: "read-docs",
    question: "当一个库的行为出乎我意料时，我的第一反应是打开它的源码。",
    weight: { introverted: 1, observant: -2, feeling: -1, prospecting: 2 },
  },
  M: {
    key: "M",
    majorGroup: "team-planning",
    minorGroup: "talk-peer",
    question: "冗长的异步来回通常不如和同事十分钟的同步沟通。",
    weight: { introverted: -3, observant: -1, feeling: 1, prospecting: 1 },
  },
  N: {
    key: "N",
    majorGroup: "personal-writing-code",
    minorGroup: "structure-code",
    question: "我自底向上构建——先写小组件，再组合。",
    weight: { introverted: 1, observant: 1, feeling: 0, prospecting: -1 },
  },
  N3: {
    key: "N3",
    majorGroup: "personal-writing-code",
    minorGroup: "make-readable",
    question: "比起一行巧妙但像谜语一样的代码，我宁愿多写三行。",
    weight: { introverted: 1, observant: 1, feeling: 0, prospecting: -1 },
  },
  Nu: {
    key: "Nu",
    majorGroup: "personal-firming-up",
    minorGroup: "handle-debt",
    question:
      "如果我碰到一个有技术债的文件，我通常会让它比我看到时更干净一些。",
    weight: { introverted: 0, observant: 0, feeling: 1, prospecting: -2 },
  },
  O: {
    key: "O",
    majorGroup: "personal-writing-code",
    minorGroup: "scope-task",
    question:
      "我会努力让任务的第一遍保持严格的范围，即使我看到附近有可以改进的地方。",
    weight: { introverted: 0, observant: 0, feeling: 0, prospecting: -2 },
  },
  OG: {
    key: "OG",
    majorGroup: "team-emotional",
    minorGroup: "sit-owner",
    question: "我会直接指出代码负责人的尖锐措辞——资历不是语气差的借口。",
    weight: { introverted: -3, observant: -1, feeling: -2, prospecting: 0 },
  },
  OZ: {
    key: "OZ",
    majorGroup: "personal-writing-code",
    minorGroup: "polish-code",
    question: "代码的美观不如「写错了能不能五分钟内重写」来得重要。",
    weight: { introverted: 0, observant: 1, feeling: -2, prospecting: 3 },
  },
  Ow: {
    key: "Ow",
    majorGroup: "team-code-review",
    minorGroup: "take-report",
    question:
      "有时我从下属的审查中学到的比资深同事的更多，因为他们的视角更新鲜。",
    weight: { introverted: -3, observant: 0, feeling: 1, prospecting: 1 },
  },
  P: {
    key: "P",
    majorGroup: "personal-writing-code",
    minorGroup: "shape-commits",
    question: "一个方便 bisect 的提交历史值得花额外功夫精心整理提交。",
    weight: { introverted: 1, observant: 2, feeling: 0, prospecting: -2 },
  },
  PJ: {
    key: "PJ",
    majorGroup: "team-emotional",
    minorGroup: "sit-report",
    question: "我会和下属明确沟通语气方面的期望——双方态度尖锐都不可接受。",
    weight: { introverted: -2, observant: 1, feeling: -1, prospecting: -1 },
  },
  PK: {
    key: "PK",
    majorGroup: "team-emotional",
    minorGroup: "sit-peer",
    question: "和同事发生激烈交流后，我会离开键盘冷静一下再回复。",
    weight: { introverted: 2, observant: -1, feeling: 2, prospecting: 0 },
  },
  Pk: {
    key: "Pk",
    majorGroup: "personal-planning",
    minorGroup: "pick-dependency",
    question:
      "外部依赖通常有比我自己的代码更多的人测试过，这是倾向于使用它们的一个理由。",
    weight: { introverted: -1, observant: 1, feeling: -1, prospecting: 0 },
  },
  Pm: {
    key: "Pm",
    majorGroup: "personal-firming-up",
    minorGroup: "design-testable",
    question:
      "对于预计会丢弃的代码，我会跳过测试——只有形态稳定后写测试才有价值。",
    weight: { introverted: 0, observant: -1, feeling: -1, prospecting: 2 },
  },
  Q: {
    key: "Q",
    majorGroup: "personal-planning",
    minorGroup: "plan-work",
    question:
      "我经常在没有清晰计划的情况下就开始写代码，让计划从代码中自然浮现。",
    weight: { introverted: -1, observant: -1, feeling: 0, prospecting: 3 },
  },
  Q0: {
    key: "Q0",
    majorGroup: "personal-planning",
    minorGroup: "read-docs",
    question: "比起冒着误解文档的风险，我更愿意花一个小时读一个库的源码。",
    weight: { introverted: 2, observant: -2, feeling: -1, prospecting: 2 },
  },
  Q0r: {
    key: "Q0r",
    majorGroup: "personal-firming-up",
    minorGroup: "explore-code",
    question:
      "把注意力集中在当前改动上让我保持产出——我没时间在工作时间里随意探索。",
    weight: { introverted: 1, observant: 2, feeling: 0, prospecting: 1 },
  },
  QQ: {
    key: "QQ",
    majorGroup: "team-planning",
    minorGroup: "talk-pm",
    question:
      "项目经理模糊的任务描述是一个危险信号——比起在不清晰的需求上开工，我宁愿推迟启动。",
    weight: { introverted: 0, observant: -1, feeling: -2, prospecting: -1 },
  },
  Qm: {
    key: "Qm",
    majorGroup: "team-planning",
    minorGroup: "talk-peer",
    question: "即使我对方案很有信心，和同事聊一遍通常也能让它更完善。",
    weight: { introverted: -2, observant: -1, feeling: 1, prospecting: 1 },
  },
  Qs: {
    key: "Qs",
    majorGroup: "team-code-review",
    minorGroup: "take-owner",
    question: "当代码负责人要求我改一些东西时，即使我不同意，我通常也会照做。",
    weight: { introverted: -1, observant: 1, feeling: 1, prospecting: 0 },
  },
  R: {
    key: "R",
    majorGroup: "personal-firming-up",
    minorGroup: "explore-code",
    question: "写一个新的辅助函数之前，我会在代码库中搜索是否已经有类似的。",
    weight: { introverted: 1, observant: 0, feeling: 0, prospecting: -2 },
  },
  RP: {
    key: "RP",
    majorGroup: "personal-writing-code",
    minorGroup: "structure-code",
    question: "模块布局的图示或草图能在我开始写代码时节省好几个小时。",
    weight: { introverted: 1, observant: 1, feeling: 0, prospecting: -1 },
  },
  RP0: {
    key: "RP0",
    majorGroup: "personal-writing-code",
    minorGroup: "write-comments",
    question: "我很少写注释——我想说的大部分内容已经在代码里了。",
    weight: { introverted: 0, observant: 1, feeling: -3, prospecting: 0 },
  },
  S: {
    key: "S",
    majorGroup: "team-emotional",
    minorGroup: "sit-peer",
    question: "如果同事对我态度尖锐，我更愿意直接谈开，而不是闷在心里。",
    weight: { introverted: -3, observant: -1, feeling: 1, prospecting: 0 },
  },
  S6: {
    key: "S6",
    majorGroup: "team-emotional",
    minorGroup: "sit-report",
    question:
      "当下属对我态度尖锐时，这尤其难受，因为我觉得他们的体验也是我的责任。",
    weight: { introverted: 1, observant: -1, feeling: 3, prospecting: 0 },
  },
  Sp: {
    key: "Sp",
    majorGroup: "team-code-review",
    minorGroup: "take-owner",
    question:
      "当代码负责人的审查评论不够清楚时，我会追问——比起猜测我更愿意确认。",
    weight: { introverted: -1, observant: 1, feeling: 1, prospecting: -1 },
  },
  T: {
    key: "T",
    majorGroup: "team-code-review",
    minorGroup: "review-report",
    question:
      "审查下属的代码一定程度上是在教学——我会解释「为什么」，而不仅仅是「是什么」。",
    weight: { introverted: -2, observant: 0, feeling: 2, prospecting: -1 },
  },
  Tp: {
    key: "Tp",
    majorGroup: "personal-planning",
    minorGroup: "read-docs",
    question: "学习一个库的最好方式是看它的测试和示例，而不是它的 README。",
    weight: { introverted: 1, observant: -1, feeling: 0, prospecting: 2 },
  },
  U: {
    key: "U",
    majorGroup: "team-planning",
    minorGroup: "talk-peer",
    question:
      "比起约一通电话，我更愿意给同事发一份书面文档——他们有空时再回复就好。",
    weight: { introverted: 3, observant: 1, feeling: -2, prospecting: -1 },
  },
  V: {
    key: "V",
    majorGroup: "personal-writing-code",
    minorGroup: "name-variables",
    question: "变量名应该包含足够的上下文信息，让我不用翻页就能理解。",
    weight: { introverted: 1, observant: 1, feeling: 1, prospecting: -1 },
  },
  Ve: {
    key: "Ve",
    majorGroup: "personal-planning",
    minorGroup: "plan-work",
    question: "一旦我确定了一个方案，除非有很强的理由，否则我会坚持下去。",
    weight: { introverted: 0, observant: 1, feeling: -1, prospecting: -3 },
  },
  Vs: {
    key: "Vs",
    majorGroup: "team-code-review",
    minorGroup: "take-report",
    question:
      "当我反驳下属的审查意见时，我会解释理由，而不只是说「不」——他们需要了解背景。",
    weight: { introverted: -2, observant: 1, feeling: 1, prospecting: -1 },
  },
  Vv: {
    key: "Vv",
    majorGroup: "personal-firming-up",
    minorGroup: "stop-task",
    question: "一旦主流程跑通我就发布——边界情况可以在后续修复。",
    weight: { introverted: 0, observant: -1, feeling: -1, prospecting: 3 },
  },
  W: {
    key: "W",
    majorGroup: "team-code-review",
    minorGroup: "take-report",
    question:
      "当下属审查我的代码时，我要花些力气才不会不自觉地轻视他们的意见。",
    weight: { introverted: -1, observant: -1, feeling: 1, prospecting: 0 },
  },
  X: {
    key: "X",
    majorGroup: "personal-writing-code",
    minorGroup: "make-readable",
    question:
      "如果一段代码包含太多想法，我会提取辅助函数，直到每一段都像散文一样易读。",
    weight: { introverted: 0, observant: 1, feeling: 0, prospecting: -1 },
  },
  Xv: {
    key: "Xv",
    majorGroup: "team-code-review",
    minorGroup: "take-peer",
    question: "如果同事的审查评论明显有误，我会跳过继续往前走。",
    weight: { introverted: 1, observant: -2, feeling: -2, prospecting: 2 },
  },
  Y: {
    key: "Y",
    majorGroup: "personal-planning",
    minorGroup: "plan-work",
    question:
      "开始之前我会估算任务，哪怕只是粗略估计，这样我能知道是否偏离了轨道。",
    weight: { introverted: 1, observant: 1, feeling: -1, prospecting: -2 },
  },
  Y1: {
    key: "Y1",
    majorGroup: "team-code-review",
    minorGroup: "take-owner",
    question: "当我有把握时，我会和代码负责人据理力争——资历浅不是让步的理由。",
    weight: { introverted: -3, observant: -2, feeling: -2, prospecting: 0 },
  },
  Z: {
    key: "Z",
    majorGroup: "personal-writing-code",
    minorGroup: "polish-code",
    question: "和丑陋的代码较劲浪费了我本可以用来解决真正问题的时间。",
    weight: { introverted: 0, observant: 1, feeling: -3, prospecting: 2 },
  },
  ZW: {
    key: "ZW",
    majorGroup: "personal-writing-code",
    minorGroup: "write-comments",
    question:
      "引用工单、事件或链接的注释能为读者提供一种我无法内联的上下文恢复方式。",
    weight: { introverted: 1, observant: 1, feeling: 0, prospecting: -1 },
  },
  b: {
    key: "b",
    majorGroup: "team-emotional",
    minorGroup: "sit-peer",
    question: "同事的尖锐言辞对我影响不大——我能把内容和语气分开。",
    weight: { introverted: -2, observant: 1, feeling: -2, prospecting: 0 },
  },
  b6: {
    key: "b6",
    majorGroup: "team-emotional",
    minorGroup: "sit-report",
    question: "我提醒自己，下属态度尖锐可能是某些我应该了解的问题的表现。",
    weight: { introverted: 1, observant: -1, feeling: 3, prospecting: 0 },
  },
  b9: {
    key: "b9",
    majorGroup: "personal-planning",
    minorGroup: "plan-work",
    question: "较长的任务我会写下里程碑，以便知道自己是否落后了。",
    weight: { introverted: 1, observant: 1, feeling: 0, prospecting: -2 },
  },
  bY: {
    key: "bY",
    majorGroup: "personal-writing-code",
    minorGroup: "write-todos",
    question: "一个在代码中留了六个月的 TODO 就是失败——我宁愿处理掉或删掉它。",
    weight: { introverted: 0, observant: 1, feeling: 0, prospecting: -3 },
  },
  bc: {
    key: "bc",
    majorGroup: "team-code-review",
    minorGroup: "take-peer",
    question:
      "我会回应每一条同事的审查评论，即使是我不同意的——它们值得一个回复。",
    weight: { introverted: -2, observant: 1, feeling: 1, prospecting: -3 },
  },
  c: {
    key: "c",
    majorGroup: "team-code-review",
    minorGroup: "review-report",
    question: "我会仔细把控对下属 PR 反馈的节奏——一次给太多会让人招架不住。",
    weight: { introverted: 1, observant: -1, feeling: 2, prospecting: 0 },
  },
  c3: {
    key: "c3",
    majorGroup: "personal-writing-code",
    minorGroup: "name-variables",
    question: "审查时我会反复重命名变量，试图找到最清晰的表达。",
    weight: { introverted: 1, observant: 0, feeling: 0, prospecting: -1 },
  },
  cC: {
    key: "cC",
    majorGroup: "personal-writing-code",
    minorGroup: "make-readable",
    question: "写完代码后我会重新读一遍，假装自己从未见过它。",
    weight: { introverted: 1, observant: 1, feeling: -1, prospecting: -1 },
  },
  cg: {
    key: "cg",
    majorGroup: "personal-writing-code",
    minorGroup: "shape-commits",
    question: "提交 PR 之前我会重写提交记录，让历史从头到尾读起来清晰连贯。",
    weight: { introverted: 2, observant: 1, feeling: 1, prospecting: -3 },
  },
  d: {
    key: "d",
    majorGroup: "team-code-review",
    minorGroup: "review-owner",
    question:
      "看到可疑之处时我会问代码负责人理由——他们往往知道一些我不知道的事。",
    weight: { introverted: -1, observant: 1, feeling: 1, prospecting: -1 },
  },
  d5: {
    key: "d5",
    majorGroup: "team-emotional",
    minorGroup: "sit-peer",
    question: "同事对我态度尖锐时，我会假设他们只是那天不顺。",
    weight: { introverted: -1, observant: 1, feeling: 1, prospecting: 0 },
  },
  dC: {
    key: "dC",
    majorGroup: "personal-writing-code",
    minorGroup: "polish-code",
    question: "我会注意别人代码中的细微美学选择，并借鉴我喜欢的。",
    weight: { introverted: 1, observant: 1, feeling: 0, prospecting: 1 },
  },
  dE: {
    key: "dE",
    majorGroup: "team-code-review",
    minorGroup: "take-report",
    question: "当下属在我的代码中发现了 bug，我会刻意当众感谢他们。",
    weight: { introverted: -2, observant: -1, feeling: 2, prospecting: 0 },
  },
  dQ: {
    key: "dQ",
    majorGroup: "personal-writing-code",
    minorGroup: "make-readable",
    question: "可读性主要在于符合读者对该语言和框架的预期。",
    weight: { introverted: 1, observant: 2, feeling: -2, prospecting: 0 },
  },
  du: {
    key: "du",
    majorGroup: "personal-writing-code",
    minorGroup: "make-readable",
    question: "对我来说，简洁惯用的代码比冗长的分步代码更易读。",
    weight: { introverted: 0, observant: -2, feeling: -2, prospecting: 0 },
  },
  e: {
    key: "e",
    majorGroup: "personal-firming-up",
    minorGroup: "handle-debt",
    question: "技术债只是尚未被优先安排的工作——它没有道德包袱。",
    weight: { introverted: 0, observant: 1, feeling: -3, prospecting: 1 },
  },
  ek: {
    key: "ek",
    majorGroup: "personal-firming-up",
    minorGroup: "think-security",
    question: "发布每个新端点之前，我都会考虑最坏情况下的滥用可能。",
    weight: { introverted: 1, observant: 1, feeling: -2, prospecting: -2 },
  },
  f: {
    key: "f",
    majorGroup: "personal-firming-up",
    minorGroup: "stop-task",
    question: "我发现自己总是发布得比应该的晚一点，想再多把一件事做好。",
    weight: { introverted: 1, observant: 1, feeling: 1, prospecting: -2 },
  },
  fH: {
    key: "fH",
    majorGroup: "team-planning",
    minorGroup: "talk-report",
    question: "对下属来说，听到「我会这样做」比「你自己想办法」更有帮助。",
    weight: { introverted: -2, observant: 1, feeling: 1, prospecting: -1 },
  },
  fO: {
    key: "fO",
    majorGroup: "team-planning",
    minorGroup: "talk-owner",
    question:
      "如果代码负责人的设计有问题，我会直说——所有权不代表他们就是对的。",
    weight: { introverted: -2, observant: -1, feeling: -2, prospecting: 0 },
  },
  ft: {
    key: "ft",
    majorGroup: "team-code-review",
    minorGroup: "review-report",
    question: "比较严厉的反馈我会私信下属，而不是放在公开的审查评论中。",
    weight: { introverted: 1, observant: 1, feeling: 1, prospecting: 0 },
  },
  fu: {
    key: "fu",
    majorGroup: "team-code-review",
    minorGroup: "review-owner",
    question: "代码负责人的代码应该和其他人的一样受到审视——甚至更多。",
    weight: { introverted: -2, observant: 1, feeling: -2, prospecting: -1 },
  },
  g: {
    key: "g",
    majorGroup: "personal-planning",
    minorGroup: "break-project",
    question:
      "如果一个任务没法一次性装进脑子里，我会先停下来分解，再写任何代码。",
    weight: { introverted: 1, observant: 1, feeling: 0, prospecting: -2 },
  },
  gN: {
    key: "gN",
    majorGroup: "personal-firming-up",
    minorGroup: "stop-task",
    question: "一个任务做完是因为我说服了自己，而不是因为某个清单打了勾。",
    weight: { introverted: 1, observant: -2, feeling: 1, prospecting: 2 },
  },
  gl: {
    key: "gl",
    majorGroup: "personal-writing-code",
    minorGroup: "make-readable",
    question: "代码读起来像我口头描述问题的方式时，感觉最对。",
    weight: { introverted: 0, observant: -1, feeling: 0, prospecting: 0 },
  },
  gs: {
    key: "gs",
    majorGroup: "team-code-review",
    minorGroup: "take-report",
    question: "下属发现了我遗漏的问题，说明代码审查流程在起作用。",
    weight: { introverted: -1, observant: 1, feeling: 1, prospecting: 0 },
  },
  h: {
    key: "h",
    majorGroup: "team-planning",
    minorGroup: "talk-pm",
    question:
      "我会尽早向项目经理展现权衡和风险，即使这些不在我被问到的范围内。",
    weight: { introverted: -2, observant: 1, feeling: 1, prospecting: -1 },
  },
  hW: {
    key: "hW",
    majorGroup: "personal-planning",
    minorGroup: "break-project",
    question: "工作时我会打开一份子任务清单，完成一项就划掉一项。",
    weight: { introverted: 1, observant: 2, feeling: 0, prospecting: -2 },
  },
  hw: {
    key: "hw",
    majorGroup: "personal-planning",
    minorGroup: "plan-work",
    question: "一份粗略的书面计划能帮我避免本来会犯的错误起步。",
    weight: { introverted: 1, observant: -1, feeling: 0, prospecting: -1 },
  },
  i: {
    key: "i",
    majorGroup: "team-planning",
    minorGroup: "talk-peer",
    question: "任务开始的第一个小时和同事结对，能让整个任务更顺畅。",
    weight: { introverted: -3, observant: -1, feeling: 1, prospecting: 0 },
  },
  iD: {
    key: "iD",
    majorGroup: "personal-firming-up",
    minorGroup: "stop-task",
    question: "发布是最难的部分——一旦接近完成，我会推动关闭任务而不是延长它。",
    weight: { introverted: -2, observant: 1, feeling: -1, prospecting: 1 },
  },
  iL: {
    key: "iL",
    majorGroup: "team-code-review",
    minorGroup: "take-peer",
    question: "一次粗暴的同事审查会让我有点丧气，即使我知道反馈是对的。",
    weight: { introverted: 2, observant: -1, feeling: 2, prospecting: 0 },
  },
  j: {
    key: "j",
    majorGroup: "personal-firming-up",
    minorGroup: "design-testable",
    question: "接入真实系统的集成测试比五十个单元测试更有价值。",
    weight: { introverted: 0, observant: -1, feeling: 0, prospecting: 2 },
  },
  j9: {
    key: "j9",
    majorGroup: "team-code-review",
    minorGroup: "review-peer",
    question: "同事审查中我会有选择地提意见——每件小事都指出来会损害关系。",
    weight: { introverted: 1, observant: -1, feeling: 1, prospecting: 1 },
  },
  jK: {
    key: "jK",
    majorGroup: "personal-writing-code",
    minorGroup: "scope-task",
    question:
      "如果能在同一个 PR 里顺手修个附近的小 bug，我就会做——拆分它感觉是没意义的额外开销。",
    weight: { introverted: 0, observant: -1, feeling: 1, prospecting: 3 },
  },
  jc: {
    key: "jc",
    majorGroup: "team-code-review",
    minorGroup: "take-peer",
    question:
      "比起争论，我更愿意接受同事审查中的吹毛求疵——代码很少值得为之死磕。",
    weight: { introverted: -1, observant: -1, feeling: 1, prospecting: 1 },
  },
  jv: {
    key: "jv",
    majorGroup: "personal-planning",
    minorGroup: "pick-dependency",
    question: "一个一年没发版的依赖让我比一直在发版的更担心。",
    weight: { introverted: 1, observant: 2, feeling: -1, prospecting: -1 },
  },
  k: {
    key: "k",
    majorGroup: "personal-firming-up",
    minorGroup: "stop-task",
    question: "我心中有一个清晰的「完成」定义，不达标我不发布。",
    weight: { introverted: 1, observant: 2, feeling: 0, prospecting: -3 },
  },
  kP: {
    key: "kP",
    majorGroup: "team-code-review",
    minorGroup: "take-peer",
    question:
      "尖锐的同事审查评论是一种馈赠——我宁愿现在收到，也不希望在生产环境中发现问题。",
    weight: { introverted: -2, observant: 1, feeling: -2, prospecting: 0 },
  },
  kt: {
    key: "kt",
    majorGroup: "personal-writing-code",
    minorGroup: "name-variables",
    question: "命名始终不如代码本身精确——我不会在上面过度投入。",
    weight: { introverted: 0, observant: -2, feeling: -2, prospecting: 2 },
  },
  l: {
    key: "l",
    majorGroup: "team-planning",
    minorGroup: "talk-pm",
    question: "面对看似随意的截止日期，即使尴尬我也会强烈反对。",
    weight: { introverted: -2, observant: 1, feeling: -2, prospecting: 0 },
  },
  l2: {
    key: "l2",
    majorGroup: "personal-writing-code",
    minorGroup: "write-comments",
    question:
      "解释非显而易见的不变量或假设的注释是必不可少的——代码本身说不清楚。",
    weight: { introverted: 1, observant: 1, feeling: 1, prospecting: 0 },
  },
  lY: {
    key: "lY",
    majorGroup: "personal-writing-code",
    minorGroup: "name-variables",
    question: "如果一个变量的名字需要注释来解释，说明名字太短了。",
    weight: { introverted: 1, observant: -1, feeling: 1, prospecting: -1 },
  },
  m: {
    key: "m",
    majorGroup: "team-emotional",
    minorGroup: "sit-report",
    question: "当下属态度尖锐时，我要注意不用权威来终止对话。",
    weight: { introverted: 2, observant: -1, feeling: 1, prospecting: 0 },
  },
  mD: {
    key: "mD",
    majorGroup: "personal-firming-up",
    minorGroup: "design-testable",
    question: "我通常先写代码，再想怎么测试。",
    weight: { introverted: 0, observant: 1, feeling: 0, prospecting: 2 },
  },
  mN: {
    key: "mN",
    majorGroup: "team-code-review",
    minorGroup: "review-peer",
    question: "审查同事的代码和自己写代码学到的一样多。",
    weight: { introverted: 1, observant: 1, feeling: 1, prospecting: 1 },
  },
  me: {
    key: "me",
    majorGroup: "personal-writing-code",
    minorGroup: "write-todos",
    question:
      "如果我现在能处理掉那个边界情况，我宁愿做了，也不留一个可能搁置数月的 TODO。",
    weight: { introverted: 0, observant: 0, feeling: 0, prospecting: -2 },
  },
  n: {
    key: "n",
    majorGroup: "team-code-review",
    minorGroup: "take-report",
    question: "当下属审查我的代码时，我认真对待他们的反馈——不带防御心理。",
    weight: { introverted: -1, observant: 0, feeling: 2, prospecting: 0 },
  },
  nD: {
    key: "nD",
    majorGroup: "personal-firming-up",
    minorGroup: "design-testable",
    question: "如果没人真的写测试，为可测试性而设计反而可能让代码变差。",
    weight: { introverted: 0, observant: 1, feeling: 1, prospecting: 2 },
  },
  nk: {
    key: "nk",
    majorGroup: "team-code-review",
    minorGroup: "review-owner",
    question: "评论之前我会把代码负责人的改动再读一遍——我想确认无误。",
    weight: { introverted: 1, observant: 1, feeling: 1, prospecting: -1 },
  },
  np: {
    key: "np",
    majorGroup: "personal-writing-code",
    minorGroup: "write-todos",
    question: "我随手就会写 TODO——大部分最终都能发挥价值。",
    weight: { introverted: -1, observant: -1, feeling: 0, prospecting: 2 },
  },
  o: {
    key: "o",
    majorGroup: "personal-firming-up",
    minorGroup: "explore-code",
    question: "我喜欢在代码库里闲逛——总能发现一些我没在找但很有用的东西。",
    weight: { introverted: 1, observant: -2, feeling: 0, prospecting: 3 },
  },
  oL: {
    key: "oL",
    majorGroup: "team-code-review",
    minorGroup: "review-peer",
    question:
      "我会快速完成同事的代码审查，即使可能漏掉一些——阻塞别人的工作有实际成本。",
    weight: { introverted: -2, observant: -1, feeling: 1, prospecting: 2 },
  },
  od: {
    key: "od",
    majorGroup: "team-planning",
    minorGroup: "talk-pm",
    question:
      "当项目经理的需求描述不够详细时，我会按自己认为正确的方式决定，事后再标记。",
    weight: { introverted: 1, observant: -2, feeling: -2, prospecting: 3 },
  },
  p: {
    key: "p",
    majorGroup: "team-planning",
    minorGroup: "talk-peer",
    question:
      "我最擅长边说边想——和同事的白板讨论比任何深度工作时间都能更快解除障碍。",
    weight: { introverted: -3, observant: -1, feeling: 1, prospecting: 1 },
  },
  pF: {
    key: "pF",
    majorGroup: "team-code-review",
    minorGroup: "take-peer",
    question:
      "我会告诉同事他们的审查对我有帮助——没有反馈信号的审查会让人觉得孤独。",
    weight: { introverted: -2, observant: -1, feeling: 2, prospecting: 0 },
  },
  pQ: {
    key: "pQ",
    majorGroup: "team-planning",
    minorGroup: "talk-report",
    question:
      "我的下属知道他们可以把不成熟的想法带给我——我把早期思考当作优点，而非缺点。",
    weight: { introverted: -2, observant: -2, feeling: 1, prospecting: 3 },
  },
  pR: {
    key: "pR",
    majorGroup: "personal-firming-up",
    minorGroup: "stop-task",
    question: "知道何时停下来对我来说比知道下一步做什么更难。",
    weight: { introverted: 1, observant: -1, feeling: 1, prospecting: 0 },
  },
  q: {
    key: "q",
    majorGroup: "personal-writing-code",
    minorGroup: "write-comments",
    question:
      "每个公开函数都值得一段简短的文档字符串，无论它看起来多么显而易见。",
    weight: { introverted: 1, observant: 2, feeling: 1, prospecting: -2 },
  },
  qG: {
    key: "qG",
    majorGroup: "personal-writing-code",
    minorGroup: "name-variables",
    question: "对于生命周期短的局部变量，单字母命名往往比长名字更清晰。",
    weight: { introverted: 0, observant: 1, feeling: -3, prospecting: 0 },
  },
  qy: {
    key: "qy",
    majorGroup: "personal-firming-up",
    minorGroup: "design-testable",
    question: "即使在写任何测试之前，我就会有意识地让代码易于测试。",
    weight: { introverted: 1, observant: -1, feeling: -2, prospecting: -2 },
  },
  r: {
    key: "r",
    majorGroup: "team-code-review",
    minorGroup: "take-owner",
    question:
      "当代码负责人审查我的代码时，我会给他们的评论更多权重，因为他们拥有更多上下文。",
    weight: { introverted: -1, observant: 1, feeling: 1, prospecting: -1 },
  },
  rG: {
    key: "rG",
    majorGroup: "personal-writing-code",
    minorGroup: "structure-code",
    question: "写一个功能之前，我通常已经知道它会放在哪些文件和模块里。",
    weight: { introverted: 1, observant: 0, feeling: 0, prospecting: -2 },
  },
  rT: {
    key: "rT",
    majorGroup: "team-code-review",
    minorGroup: "take-peer",
    question: "同事审查后我会重新阅读自己的 PR，试图用他们的视角来看。",
    weight: { introverted: 2, observant: 1, feeling: 1, prospecting: -1 },
  },
  rTD: {
    key: "rTD",
    majorGroup: "team-code-review",
    minorGroup: "review-peer",
    question: "同事代码审查时，我会先说哪些地方做得好，再指出不足。",
    weight: { introverted: 1, observant: -1, feeling: 1, prospecting: 0 },
  },
  rt: {
    key: "rt",
    majorGroup: "team-code-review",
    minorGroup: "review-report",
    question: "如果下属已经深思熟虑过，除非明显有误，我倾向于批准。",
    weight: { introverted: -1, observant: 1, feeling: 1, prospecting: 2 },
  },
  s: {
    key: "s",
    majorGroup: "team-planning",
    minorGroup: "talk-owner",
    question:
      "代码负责人有我没有的上下文，所以意见不一致时我倾向于尊重他们的偏好。",
    weight: { introverted: -1, observant: 1, feeling: 1, prospecting: -1 },
  },
  sj: {
    key: "sj",
    majorGroup: "personal-planning",
    minorGroup: "read-docs",
    question: "我足够信任一个库的公开文档，以至于用之前很少去看它的源码。",
    weight: { introverted: 0, observant: 3, feeling: -1, prospecting: 0 },
  },
  t: {
    key: "t",
    majorGroup: "personal-firming-up",
    minorGroup: "handle-debt",
    question: "有些技术债是战略性的——当替换它为时过早时，我会保留它。",
    weight: { introverted: 1, observant: 1, feeling: -1, prospecting: 1 },
  },
  t2: {
    key: "t2",
    majorGroup: "team-planning",
    minorGroup: "talk-owner",
    question: "写第一行代码之前，我会问代码负责人他们期望这个改动是什么样的。",
    weight: { introverted: -1, observant: 2, feeling: 1, prospecting: -3 },
  },
  tY: {
    key: "tY",
    majorGroup: "personal-firming-up",
    minorGroup: "think-security",
    question: "一个小的安全疏忽是那种让我失眠的错误。",
    weight: { introverted: 1, observant: 0, feeling: -1, prospecting: 0 },
  },
  tb: {
    key: "tb",
    majorGroup: "personal-writing-code",
    minorGroup: "scope-task",
    question: "随着我的了解加深，任务的范围也在扩大——假装范围固定是自欺欺人。",
    weight: { introverted: -1, observant: -2, feeling: 0, prospecting: 3 },
  },
  u: {
    key: "u",
    majorGroup: "team-code-review",
    minorGroup: "review-peer",
    question: "挑剔细节很重要——只抓大问题的审查错过了一半的价值。",
    weight: { introverted: -1, observant: 2, feeling: -1, prospecting: -1 },
  },
  uO: {
    key: "uO",
    majorGroup: "team-code-review",
    minorGroup: "review-owner",
    question:
      "审查代码负责人的代码让人不舒服——比起冒着搞错的风险，我更愿意直接批准。",
    weight: { introverted: 1, observant: 1, feeling: 2, prospecting: 1 },
  },
  v: {
    key: "v",
    majorGroup: "team-emotional",
    minorGroup: "sit-owner",
    question:
      "我倾向于认为代码负责人的尖锐言辞反映了一个我应该解决的真实问题。",
    weight: { introverted: 1, observant: 1, feeling: 1, prospecting: -1 },
  },
  vO: {
    key: "vO",
    majorGroup: "team-emotional",
    minorGroup: "sit-report",
    question: "下属的尖锐时刻对我影响不大——权力差异削弱了它的刺痛感。",
    weight: { introverted: -2, observant: 1, feeling: -2, prospecting: 1 },
  },
  vR: {
    key: "vR",
    majorGroup: "personal-writing-code",
    minorGroup: "polish-code",
    question: "我会花额外时间让代码感觉恰到好处，即使审查者不会注意到差别。",
    weight: { introverted: 1, observant: -1, feeling: 2, prospecting: -1 },
  },
  vc: {
    key: "vc",
    majorGroup: "personal-planning",
    minorGroup: "break-project",
    question: "一个新任务在我脑中是一个形状，而不是一份步骤清单。",
    weight: { introverted: 0, observant: -2, feeling: 0, prospecting: 2 },
  },
  vd: {
    key: "vd",
    majorGroup: "team-planning",
    minorGroup: "talk-report",
    question: "我经常跟下属沟通——我宁愿过度沟通，也不想让他们感到迷茫。",
    weight: { introverted: -3, observant: 1, feeling: 3, prospecting: -1 },
  },
  vk: {
    key: "vk",
    majorGroup: "personal-planning",
    minorGroup: "pick-dependency",
    question: "在库之间做选择时，比起纸面上最好看的，我更看重社区中流行的。",
    weight: { introverted: -2, observant: 3, feeling: 1, prospecting: 1 },
  },
  vz: {
    key: "vz",
    majorGroup: "personal-firming-up",
    minorGroup: "think-security",
    question: "每当用户数据跨越信任边界时，我都会再检查一遍输入处理。",
    weight: { introverted: 1, observant: 1, feeling: -2, prospecting: -1 },
  },
  w: {
    key: "w",
    majorGroup: "personal-firming-up",
    minorGroup: "explore-code",
    question: "我会花额外时间阅读相关代码，确保我的改动符合现有模式。",
    weight: { introverted: 1, observant: 0, feeling: 1, prospecting: -1 },
  },
  wU: {
    key: "wU",
    majorGroup: "team-code-review",
    minorGroup: "take-report",
    question:
      "下属经常缺少我拥有的上下文，所以我会考虑到这个差距来衡量他们的审查评论。",
    weight: { introverted: 1, observant: 1, feeling: -2, prospecting: 0 },
  },
  wX: {
    key: "wX",
    majorGroup: "team-code-review",
    minorGroup: "take-owner",
    question: "代码负责人的评论比同事的同样评论在我心中停留更久。",
    weight: { introverted: 2, observant: -1, feeling: 2, prospecting: 0 },
  },
  x: {
    key: "x",
    majorGroup: "team-emotional",
    minorGroup: "sit-report",
    question: "我能把下属的尖锐言辞当作工作问题来处理，不会让它一直萦绕心头。",
    weight: { introverted: -2, observant: 1, feeling: -2, prospecting: 0 },
  },
  xG: {
    key: "xG",
    majorGroup: "personal-firming-up",
    minorGroup: "think-security",
    question: "安全主要是专家的事——我依赖框架和我们的基础设施来处理。",
    weight: { introverted: 0, observant: 2, feeling: -1, prospecting: 2 },
  },
  xX: {
    key: "xX",
    majorGroup: "team-emotional",
    minorGroup: "sit-peer",
    question: "当同事说了刺耳的话，之后我会在脑中反复回放一阵。",
    weight: { introverted: 2, observant: -1, feeling: 3, prospecting: 0 },
  },
  xe: {
    key: "xe",
    majorGroup: "personal-firming-up",
    minorGroup: "design-testable",
    question: "设计过程中写的测试能发现仅靠阅读代码发现不了的 bug。",
    weight: { introverted: 1, observant: 2, feeling: 0, prospecting: -2 },
  },
  y: {
    key: "y",
    majorGroup: "team-planning",
    minorGroup: "talk-pm",
    question: "给项目经理一个范围估算而不是单点估算对双方都有帮助。",
    weight: { introverted: 1, observant: 1, feeling: 1, prospecting: -1 },
  },
  yG: {
    key: "yG",
    majorGroup: "team-planning",
    minorGroup: "talk-report",
    question: "带领下属的工作不只是完成任务，还包括帮助他们成长。",
    weight: { introverted: -2, observant: 0, feeling: 0, prospecting: 0 },
  },
  yh: {
    key: "yh",
    majorGroup: "personal-firming-up",
    minorGroup: "handle-debt",
    question: "忽视技术债就像忽视慢漏水——最终它会毁掉整个房间。",
    weight: { introverted: 1, observant: -1, feeling: 1, prospecting: -1 },
  },
  z: {
    key: "z",
    majorGroup: "personal-firming-up",
    minorGroup: "stop-task",
    question: "一旦代码满足需求，我就继续往前走——进一步打磨通常看不出来。",
    weight: { introverted: 0, observant: 1, feeling: -1, prospecting: 2 },
  },
  zW: {
    key: "zW",
    majorGroup: "team-code-review",
    minorGroup: "review-report",
    question: "我会尽量保留下属的代码风格选择，即使那不是我会用的方式。",
    weight: { introverted: -1, observant: -1, feeling: 1, prospecting: 1 },
  },
  zg: {
    key: "zg",
    majorGroup: "team-code-review",
    minorGroup: "review-peer",
    question: "我会花时间认真做同事代码审查——匆忙的审查还不如不审。",
    weight: { introverted: 1, observant: 1, feeling: 1, prospecting: -2 },
  },
  zw: {
    key: "zw",
    majorGroup: "team-code-review",
    minorGroup: "review-peer",
    question: "除非我很确定，否则我的审查评论都写成问题的形式，而不是要求。",
    weight: { introverted: 1, observant: 0, feeling: 2, prospecting: 0 },
  },
} satisfies { [key: string]: Question }
